# Use Node.js base image
FROM node:20

# Set working directory
WORKDIR /usr/src/app

# Copy package files first to install deps
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Install dev tools like ts-node-dev
RUN npm install --save-dev ts-node-dev

# Expose port used by NestJS
EXPOSE 3001

# Start app in dev mode
CMD ["npm", "run", "start:dev"]

