services:
  api:
    container_name: unirise-aadhya-server
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - db  # ensures DB is up before API tries to connect
    environment:
      DATABASE_TYPE: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: aadhya_db
      NODE_ENV: development
      PORT: 3001

  db:
    image: postgres:16-alpine
    container_name: aadhya-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aadhya_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
